export const CONFIRMED = {
  READ: "READ",
  SENT: "NOT VIEWED",
  CONFIRMED: "CONFIRMED",
  SCOUTING: "SCOUTING",
  OUT: "OUT",
  UNSURE: "UNSURE",
};

export const PRIVACY = {
  OPEN: "OPEN",

  PRIVATE: "PRIVATE",
};

export const GAME_STATES = {
  PRIVATE_REGISTRATION: "PRIVATE_REGISTRATION",
  OPEN_REGISTRATION: "OPEN_REGISTRATION",
  CANCELLED: "CANCELLED",
  LIST_SET: "LIST_SET",
  GAME_RUNNING_FULL: "GAME_RUNNING_FULL",
  GAME_RUNNING_OPEN: "GAME_RUNNING_OPEN",
  CLOSED: "CLOSED",
};

export const SCREEN_TYPE = {
  WIDE: "WIDE",
  MEDIUM: "MEDIUM",
  MOBILE: "MOBILE",
};

export const SCREEN_WIDTH_MIN = {
  WIDE: 1100,
  MEDIUM: 650,
  MOBILE: 0,
};
