export const SET_PHONE = "SET_PHONE";

export const SET_GAME = "SET_GAME";
export const SET_GAME_S = "SET_GAME_S";
export const UPDATE_GAME_S = "UPDATE_GAME_S";
export const SET_GROUP = "SET_GROUP";

export const CREATE_GAME = "CREATE_GAME";
export const DELETE_GAME = "DELETE_GAME";
export const SET_AVATARS = "SET_AVATARS";

export const ADD_MEMBER_TO_GROUP = "ADD_MEMBER_TO_GROUP";

export const SET_MEMBER_OF_GROUP = "SET_MEMBER_OF_GROUP";

export const CREATE_HOST_GROUP = "CREATE_HOST_GROUP";
export const DELETE_HOST_GROUP = "DELETE_HOST_GROUP";
export const SET_HOST_GROUPS = "SET_HOST_GROUPS";

export const CREATE_MEMBER_GROUP = "CREATE_MEMBER_GROUP";
export const DELETE_MEMBER_GROUP = "DELETE_MEMBER_GROUP";
export const SET_MEMBER_GROUPS = "SET_MEMBER_GROUPS";

export const CREATE_AREA_GROUP = "CREATE_AREA_GROUP";
export const DELETE_AREA_GROUP = "DELETE_AREA_GROUP";
export const SET_AREA_GROUPS = "SET_AREA_GROUPS";

export const CREATE_INVITE_GROUP = "CREATE_INVITE_GROUP";
export const DELETE_INVITE_GROUP = "DELETE_INVITE_GROUP";
export const SET_INVITE_GROUPS = "SET_INVITE_GROUPS";

export const REQUEST_TO_JOIN_GROUP = "REQUEST_TO_JOIN_GROUP";
export const ACCEPT_MEMBER_IN_GROUP = "ACCEPT_MEMBER_IN_GROUP";

export const SET_MEMBERS_IN_AREA = "SET_MEMBERS_IN_AREA";
export const FOLLOW_MEMBER = "FOLLOW_MEMBER";
export const UNFOLLOW_MEMBER = "UNFOLLOW_MEMBER";
export const ADD_MEMBER_TO_AREA = "ADD_MEMBER_TO_AREA";

export const SET_USER_PHOTOS = "SET_USER_PHOTOS";
export const ADD_USER_PHOTO = "ADD_USER_PHOTO";

export const SET_GAME_TRANSACTIONS = "SET_GAME_TRANSACTIONS";
export const CREATE_GAME_TRANSACTION = "CREATE_GAME_TRANSACTION";

export const SET_OVERLAY = "SET_OVERLAY";

export const SET_DISPLAY_NAME = "SET_DISPLAY_NAME";
export const SET_PHOTO_URL = "SET_PHOTO_URL";

export const SET_TOUCH = "SET_TOUCH";

export const SET_DM = "SET_DM";

export const ADD_URM = "ADD_URM";
export const REMOVE_URM = "REMOVE_URM";

export const UPDATE_A_GAMES_THUMBNAIL = "UPDATE_A_GAMES_THUMBNAIL";

export const SET_DRAG_POSITION = "SET_DRAG_POSITION";

export const REGISTER_OPEN_SEAT = "REGISTER_OPEN_SEAT";
export const CLEAR_TOUCH = "CLEAR_TOUCH";
export const RETURN_MEMBER = "RETURN_MEMBER";
export const DROP_MEMBER = "DROP_MEMBER";
export const REGISTER_WAIT_DROP_ZONE = "REGISTER_WAIT_DROP_ZONE";
