export const SET_PHONE = "SET_PHONE";

export const SET_GAME = "SET_GAME";
export const SET_GAME_S = "SET_GAME_S";
export const UPDATE_GAME_S = "UPDATE_GAME_S";
export const SET_GROUP = "SET_GROUP";

export const CREATE_GAME = "CREATE_GAME";
export const DELETE_GAME = "DELETE_GAME";
export const SET_AVATARS = "SET_AVATARS";

export const ADD_MEMBER_TO_GROUP = "ADD_MEMBER_TO_GROUP";

export const SET_MEMBER_OF_GROUP = "SET_MEMBER_OF_GROUP";

export const CREATE_HOST_GROUP = "CREATE_HOST_GROUP";
export const DELETE_HOST_GROUP = "DELETE_HOST_GROUP";
export const SET_HOST_GROUPS = "SET_HOST_GROUPS";

export const CREATE_MEMBER_GROUP = "CREATE_MEMBER_GROUP";
export const DELETE_MEMBER_GROUP = "DELETE_MEMBER_GROUP";
export const SET_MEMBER_GROUPS = "SET_MEMBER_GROUPS";

export const CREATE_AREA_GROUP = "CREATE_AREA_GROUP";
export const DELETE_AREA_GROUP = "DELETE_AREA_GROUP";
export const SET_AREA_GROUPS = "SET_AREA_GROUPS";

export const CREATE_INVITE_GROUP = "CREATE_INVITE_GROUP";
export const DELETE_INVITE_GROUP = "DELETE_INVITE_GROUP";
export const SET_INVITE_GROUPS = "SET_INVITE_GROUPS";

export const REQUEST_TO_JOIN_GROUP = "REQUEST_TO_JOIN_GROUP";
export const ACCEPT_MEMBER_IN_GROUP = "ACCEPT_MEMBER_IN_GROUP";
